title: Misaal
description: Misaal is a platform dedicated to inspiring the actions of young
  Indian Muslims by sharing stories of high achieving individuals from the same
  community who have emerged as managers, leaders, and entrepreneurs in their
  respective fields.
logo: /assets/uploads/logo_transparent.png
logo_dark: /assets/uploads/logo_transparent.png
cover: /assets/uploads/pexels-vlad-che»õan-2892619.jpg
contact:
  email: editor@misaal.co.in
  twitter: Misaal786
  facebook: Misaal786
  instagram: Misaal786
  youtube_channel: null
